"""Generate supabase/seed.sql from data/*.json. Idempotent-ish: fixed household id."""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from nutrition_calc import NUT, calc_ingredient

BASE = os.path.join(os.path.dirname(__file__), '..')
seed = json.load(open(os.path.join(BASE, 'data', 'seed.json')))
nut = json.load(open(os.path.join(BASE, 'data', 'nutrition.json')))

HID = "11111111-1111-1111-1111-111111111111"
def q(s):
    if s is None: return 'null'
    return "'" + str(s).replace("'", "''") + "'"

out = []
out.append(f"insert into households (id, name, join_code) values ('{HID}', {q(seed['household']['name'])}, {q(seed['household']['join_code'])}) on conflict (id) do nothing;")

for it in nut['items']:
    aliases = '{' + ','.join('"%s"' % a.replace('"','') for a in it.get('aliases', [])) + '}'
    pg = it.get('piece_grams')
    out.append(
        f"insert into ingredient_nutrition (key, name_he, aliases, kcal_per_100, protein_per_100, piece_grams, source, household_id) values "
        f"({q(it['key'])}, {q(it['name_he'])}, '{aliases}'::text[], {it['kcal']}, {it['protein']}, {pg if pg else 'null'}, 'curated', null) "
        f"on conflict (key) do nothing;"
    )

from datetime import date, timedelta
today = date.today()
for p in seed['pantry']:
    opened = (today - timedelta(days=p['opened_days_ago'])).isoformat() if p.get('opened_days_ago') is not None else None
    out.append(
        f"insert into pantry_items (household_id, name, category, quantity_state, is_open, opened_at, is_protein, location, package_size, added_by) values "
        f"('{HID}', {q(p['name'])}, {q(p.get('category','אחר'))}, {q(p.get('quantity_state','full'))}, {str(p.get('is_open',False)).lower()}, {q(opened)}, "
        f"{str(p.get('is_protein',False)).lower()}, {q(p.get('location','pantry'))}, {q(p.get('package_size'))}, 'יובל');"
    )

for r in seed['recipes']:
    rid = "gen_random_uuid()"
    steps = json.dumps(r['steps'], ensure_ascii=False).replace("'", "''")
    out.append(
        f"insert into recipes (household_id, title, time_minutes, servings, steps, notes, created_by) values "
        f"('{HID}', {q(r['title'])}, {r.get('time_minutes','null')}, {r.get('servings',2)}, '{steps}'::jsonb, {q(r.get('notes'))}, 'יובל');"
    )
    # ingredients need recipe id: use a CTE per recipe
    vals = []
    for pos, ing in enumerate(r['ingredients']):
        item = NUT.get(ing['nutrition_key'])
        g, kcal, protein, matched = calc_ingredient(ing)
        vals.append(
            f"({q(ing['name'])}, {ing['amount']}, {q(ing['unit'])}, {round(g,1) if g else 'null'}, {q(ing['nutrition_key'])}, "
            f"{round(kcal,1) if kcal else 'null'}, {round(protein,2) if protein else 'null'}, {str(matched).lower()}, {pos})"
        )
    out.append(
        "insert into recipe_ingredients (recipe_id, household_id, name, amount, unit, grams, nutrition_key, kcal, protein, matched, position) "
        f"select id, '{HID}', v.name, v.amount, v.unit, v.grams, v.nutrition_key, v.kcal, v.protein, v.matched, v.position "
        f"from recipes, (values {','.join(vals)}) as v(name, amount, unit, grams, nutrition_key, kcal, protein, matched, position) "
        f"where recipes.title = {q(r['title'])} and recipes.household_id = '{HID}';"
    )

sql = '-- generated by scripts/gen_seed_sql.py; run after schema.sql\n' + '\n'.join(out) + '\n'
open(os.path.join(BASE, 'supabase', 'seed.sql'), 'w').write(sql)
print('seed.sql written:', len(out), 'statements')
